language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'USE test; CREATE TABLE users (id int(10) UNSIGNED NOT NULL, name varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL, email varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL, created datetime DEFAULT NULL, attributes text COLLATE utf8_unicode_ci) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;'
  - mysql -e 'USE test; ALTER TABLE `users` ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `email` (`email`);'
  - mysql -e 'USE test; TRUNCATE users;'
install:
  - composer install